### ISSUE TITLE
Plex HTPC for Mac & Plex for Android TV ERROR

### ISSUE THREAD

**Issue by x1ao4** [mdhiggins/PlexAutoSkip#49] opened 2023-05-29 15:14 UTC
Plex HTPC for Mac
`ERROR - Exception, removing from cache to prevent false triggers, will be restored with next sync
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
.
.
.
.
.
.
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.31.19', port=32500): Max retries exceeded with url: /player/playback/seekTo?commandID=1&offset=114367&type=video (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f7cf490>: Failed to establish a new connection: [Errno 61] Connection refused'))
`

Plex for Android TV
`ERROR - 404 Error, see https://github.com/mdhiggins/PlexAutoSkip/wiki/Troubleshooting#badrequest-error`

iOS works fine. Not sure what the problem is.

**Comment by x1ao4** [comment] 2023-05-30 12:30
I got Plex HTPC for Mac work by set ssl to False, I think. But Plex for Android TV still not working, it is a SONY BRAVIA X95J, Plex for Android TV version 9.23.0.1746.

**Comment by AngusThermo-Pyle** [comment] 2023-06-05 15:12
I see the same error woth the max retries exceeded sometimes against a Samsung AndroidTV, but in  my case it works normally some of the time, registering the websocket and skipping content.  The trouble is that when the exception is thrown for max retries, it stays running without attempting to reconnect, so the systemd service can't know to restart it and it won't function correctly until the script is restarted.  I'm currently doing this on a systemd timer every day, but that still means that it can stop working during the day.  If the exception was caught and retried, it would work correctly for my case, I suspect.

**Comment by mdhiggins** [comment] 2023-06-05 21:15
Should finally have a day off to test my nvidia shield coming up this week and see if Plex broke API support 

@AngusThermo-Pyle your issue sounds different. The actual websocket connection to the server is distinct from the requests that go to the players for seeking which is what this error is. They run on different threads and should not impact the server connection at all. Please share some logs and open up a new issue

**Comment by mdhiggins** [comment] 2023-06-07 12:36
Going to close this issue out since its a duplicate of #48, just posted some info there

**Closed as completed by mdhiggins** 2023-06-07 12:36 UTC
