### ISSUE TITLE
Error skipping on Fire TV Stick 4K 

### ISSUE THREAD

**Issue by shanethegooner** [mdhiggins/PlexAutoSkip#33] opened 2023-02-19 12:48 UTC
Recently installed this, it's working great when testing using the HTPC version of Plex on Windows but when testing on my Fire TV Stick (my main device) it doesn't skip at all. Skipper can see the session but as soon as the intro starts I get errors. I've troubleshooted by restarting Plex server and logging out and back into the Fire TV Stick. 

C:\Users\sodwy>"C:\Users\sodwy\Documents\PlexAutoSkip\main.py"
INFO - C:\Users\sodwy\AppData\Local\Programs\Python\Python37\python.exe
INFO - Loading config file C:\Users\sodwy\Documents\PlexAutoSkip\config\config.ini.
INFO - Loading custom JSON file C:\Users\sodwy\Documents\PlexAutoSkip\config\custom.json
INFO - Connecting to Plex server...
INFO - Connected to Plex server PLEXSERVER using plex.tv account
INFO - Skipper initiated and ready
WARNING - websocket connected
INFO - Found new session 8 [4556] (American Dad! s19e09 - The Curious Case of the Old Hole) AFTKA|27f6a413d526829d-com-plexapp-android viewOffset 827 shanethegooner, sessions: 0
INFO - Found skippable marker intro for media 8 [4556] (American Dad! s19e09 - The Curious Case of the Old Hole) AFTKA|27f6a413d526829d-com-plexapp-android with range 93621-119938 and viewOffset 94204
INFO - Seeking Plex for Android (TV) player playing 8 [4556] (American Dad! s19e09 - The Curious Case of the Old Hole) AFTKA|27f6a413d526829d-com-plexapp-android from 94204 to 119938
ERROR - BadRequest Error, see https://github.com/mdhiggins/PlexAutoSkip/wiki/Troubleshooting#badrequest-error
INFO - Seeking Plex for Android (TV) player playing 8 [4556] (American Dad! s19e09 - The Curious Case of the Old Hole) AFTKA|27f6a413d526829d-com-plexapp-android from 94204 to 119938
ERROR - Exception, removing from cache to prevent false triggers, will be restored with next sync
Traceback (most recent call last):
  File "C:\Users\sodwy\Documents\PlexAutoSkip\resources\skipper.py", line 247, in seekPlayerTo
    mediaWrapper.seekTo(targetOffset, player)
  File "C:\Users\sodwy\Documents\PlexAutoSkip\resources\mediaWrapper.py", line 324, in seekTo
    player.seekTo(offset)
  File "C:\Users\sodwy\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\client.py", line 377, in seekTo
    self.sendCommand('playback/seekTo', offset=offset, type=mtype)
  File "C:\Users\sodwy\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\client.py", line 232, in sendCommand
    return query(key, headers=headers)
  File "C:\Users\sodwy\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\server.py", line 755, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (500) internal_server_error; https://192-168-50-87.7c730a5c200c4f3b96220f5dcd03c16a.plex.direct:32400/player/playback/seekTo?commandID=1&offset=119938&type=video <?xml version='1.0' encoding='utf-8'?> <Response code="2000" status="FrameworkException: Unable to find player with identifier 27f6a413d526829d-com-plexapp-android">   <Traceback>Traceback (most recent call last):   File "C:\Program Files\Plex\Plex Media Server\Resources\Plug-ins-ca0c45ff8\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 843, in handle_request     result = f(**d)   File "C:\Program Files\Plex\Plex Media Server\Resources\Plug-ins-ca0c45ff8\System.bundle\Contents\Code\playerservice.py", line 50, in process_remote_command     raise FrameworkException('Unable to find player with identifier %s' % identifier) FrameworkException: Unable to find player with identifier 27f6a413d526829d-com-plexapp-android </Traceback> </Response>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sodwy\Documents\PlexAutoSkip\resources\skipper.py", line 221, in _seekTo
    self.seekPlayerTo(mediaWrapper.player, mediaWrapper, targetOffset)
  File "C:\Users\sodwy\Documents\PlexAutoSkip\resources\skipper.py", line 255, in seekPlayerTo
    return self.seekPlayerTo(self.recoverPlayer(player), mediaWrapper, targetOffset)
  File "C:\Users\sodwy\Documents\PlexAutoSkip\resources\skipper.py", line 247, in seekPlayerTo
    mediaWrapper.seekTo(targetOffset, player)
  File "C:\Users\sodwy\Documents\PlexAutoSkip\resources\mediaWrapper.py", line 324, in seekTo
    player.seekTo(offset)
  File "C:\Users\sodwy\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\client.py", line 377, in seekTo
    self.sendCommand('playback/seekTo', offset=offset, type=mtype)
  File "C:\Users\sodwy\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\client.py", line 232, in sendCommand
    return query(key, headers=headers)
  File "C:\Users\sodwy\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\client.py", line 192, in query
    raise NotFound(message)
plexapi.exceptions.NotFound: (404) not_found; http://192.168.50.19:32500/player/playback/seekTo?commandID=2&offset=11993 &type=video Failure: 404 Not Found
INFO - Found new session 8 [4556] (American Dad! s19e09 - The Curious Case of the Old Hole) AFTKA|27f6a413d526829d-com-plexapp-android viewOffset 95332 shanethegooner, sessions: 0
INFO - Found skippable marker intro for media 8 [4556] (American Dad! s19e09 - The Curious Case of the Old Hole) AFTKA|27f6a413d526829d-com-plexapp-android with range 93621-119938 and viewOffset 95332
INFO - Seeking Plex for Android (TV) player playing 8 [4556] (American Dad! s19e09 - The Curious Case of the Old Hole) AFTKA|27f6a413d526829d-com-plexapp-android from 95344 to 119938
ERROR - BadRequest Error, see https://github.com/mdhiggins/PlexAutoSkip/wiki/Troubleshooting#badrequest-error
INFO - Seeking Plex for Android (TV) player playing 8 [4556] (American Dad! s19e09 - The Curious Case of the Old Hole) AFTKA|27f6a413d526829d-com-plexapp-android from 95344 to 119938
ERROR - Exception, removing from cache to prevent false triggers, will be restored with next sync
Traceback (most recent call last):
  File "C:\Users\sodwy\Documents\PlexAutoSkip\resources\skipper.py", line 247, in seekPlayerTo
    mediaWrapper.seekTo(targetOffset, player)
  File "C:\Users\sodwy\Documents\PlexAutoSkip\resources\mediaWrapper.py", line 324, in seekTo
    player.seekTo(offset)
  File "C:\Users\sodwy\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\client.py", line 377, in seekTo
    self.sendCommand('playback/seekTo', offset=offset, type=mtype)
  File "C:\Users\sodwy\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\client.py", line 232, in sendCommand
    return query(key, headers=headers)
  File "C:\Users\sodwy\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\server.py", line 755, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (500) internal_server_error; https://192-168-50-87.7c730a5c200c4f3b96220f5dcd03c16a.plex.direct:32400/player/playback/seekTo?commandID=1&offset=119938&type=video <?xml version='1.0' encoding='utf-8'?> <Response code="2000" status="FrameworkException: Unable to find player with identifier 27f6a413d526829d-com-plexapp-android">   <Traceback>Traceback (most recent call last):   File "C:\Program Files\Plex\Plex Media Server\Resources\Plug-ins-ca0c45ff8\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 843, in handle_request     result = f(**d)   File "C:\Program Files\Plex\Plex Media Server\Resources\Plug-ins-ca0c45ff8\System.bundle\Contents\Code\playerservice.py", line 50, in process_remote_command     raise FrameworkException('Unable to find player with identifier %s' % identifier) FrameworkException: Unable to find player with identifier 27f6a413d526829d-com-plexapp-android </Traceback> </Response>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sodwy\Documents\PlexAutoSkip\resources\skipper.py", line 221, in _seekTo
    self.seekPlayerTo(mediaWrapper.player, mediaWrapper, targetOffset)
  File "C:\Users\sodwy\Documents\PlexAutoSkip\resources\skipper.py", line 255, in seekPlayerTo
    return self.seekPlayerTo(self.recoverPlayer(player), mediaWrapper, targetOffset)
  File "C:\Users\sodwy\Documents\PlexAutoSkip\resources\skipper.py", line 247, in seekPlayerTo
    mediaWrapper.seekTo(targetOffset, player)
  File "C:\Users\sodwy\Documents\PlexAutoSkip\resources\mediaWrapper.py", line 324, in seekTo
    player.seekTo(offset)
  File "C:\Users\sodwy\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\client.py", line 377, in seekTo
    self.sendCommand('playback/seekTo', offset=offset, type=mtype)
  File "C:\Users\sodwy\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\client.py", line 232, in sendCommand
    return query(key, headers=headers)
  File "C:\Users\sodwy\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\client.py", line 192, in query
    raise NotFound(message)
plexapi.exceptions.NotFound: (404) not_found; http://192.168.50.19:32500/player/playback/seekTo?commandID=2&offset=11993 &type=video Failure: 404 Not Found

**Comment by ShanaryS** [comment] 2023-02-19 17:58
Same issue with chromecast

**Comment by mdhiggins** [comment] 2023-02-19 20:36
Make sure you try all the steps in the Badrequest Error troubleshooting

Also see

https://github.com/mdhiggins/PlexAutoSkip/issues/28

https://github.com/mdhiggins/PlexAutoSkip/issues/27

https://github.com/mdhiggins/PlexAutoSkip/issues/19

If you tried all those steps please post the local IP address of your router, plex server, and device that's not working, sometimes its a subnet issue

Other than that there's not much more I can offer, if the Plex API doesn't work on the device it can't be controlled but FireTV and Chromecast do work

**Comment by shanethegooner** [comment] 2023-02-19 20:42
Hi 

I went through the troubleshooting and checked over closed issues before posting, none of which helped me out. 

Router: 192.168.50.1
Plex Server: 192.168.50.87
Fire TV Stick: 192.168.50.19

**Comment by mdhiggins** [comment] 2023-02-19 20:50
https://github.com/mdhiggins/PlexAutoSkip/issues/3#issuecomment-1364540980

See if you can access the API on the FireTV at all using the instructions in that post and share the XML output

**Comment by shanethegooner** [comment] 2023-02-19 20:55
So going to http://192.168.50.19:32500/resources?token=>PLEXTOKEN< produced something but it's to do with YouTube?

```
<MediaContainer size="0">
<script id="youtube-hd-fjdmkanbdloodhegphphhklnjfngoffa">var ythdlog = () => {};;var ythderror = () => {};</script>
</MediaContainer>
```

**Comment by mdhiggins** [comment] 2023-02-19 20:59
https://support.plex.tv/articles/201812803-plex-companion-remote-control-issues/

That's Plex's official support document on this issue, so you can see if your client shows up too. The script depends on Plex Companion working though so if both of these things are failing not much I can do

**Comment by shanethegooner** [comment] 2023-02-19 21:09
So that shows my PC and phone but no Fire TV Stick. I guess there's not much else to do then? 

```
<MediaContainer size="2">
<script id="youtube-hd-fjdmkanbdloodhegphphhklnjfngoffa">var ythdlog = () => {};;var ythderror = () => {};</script>
<Server name="Galaxy S21 FE 5G" host="192.168.50.24" address="192.168.50.24" port="32500" machineIdentifier="d5e7d9f7632bc7e4-com-plexapp-android" version="9.15.0.38159" protocol="plex" product="Plex for Android (Mobile)" deviceClass="mobile" protocolVersion="1" protocolCapabilities="timeline,playback,mirror,playqueues,provider-playback"/>
<Server name="SHANE-PC" host="192.168.50.87" address="192.168.50.87" port="32400" machineIdentifier="qicp2wbq9k8olizu5yfvvrdy" version="1.41.0.2876-e960c9ca" protocol="plex" product="Plex for Windows" deviceClass="pc" protocolVersion="3" protocolCapabilities="timeline,playback,navigation,mirror,playqueues"/>
</MediaContainer>
```

**Comment by mdhiggins** [comment] 2023-02-19 21:15
> So going to [http://192.168.50.19:32500/resources?token=>PLEXTOKEN](http://192.168.50.19:32500/resources?token=%3EPLEXTOKEN)< produced something but it's to do with YouTube?
> 
> ```
> <MediaContainer size="0">
> <script id="youtube-hd-fjdmkanbdloodhegphphhklnjfngoffa">var ythdlog = () => {};;var ythderror = () => {};</script>
> </MediaContainer>
> ```

Well that's bizarre, I've never seen that

Are you running any browser add-ons that force YouTube to be HD that might be injecting that YouTube line? 

Otherwise it looks like an empty MediaContainer which means the Plex Companion API isn't working on that client

```xml
<MediaContainer>
<Player platformVersion="11.5.0 build 4312" protocolVersion="1" machineIdentifier="CENSORED" deviceClass="stb" platform="Roku" version="7.0.23.8111-8c8a6a9b7-Plex" protocolCapabilities="timeline,playback,playqueues" title="Living Room" product="Plex for Roku"/>
</MediaContainer>
```

It should be returning something like that

I'm not super familiar with the FireTV sticks and how they deviate from regular Android TV, do you have multiple app stores to pull from?

@DreamStatic just had a recent post about getting things working using a FireTV Stick, maybe they can shed some light since clearly the hardware is capable

**Comment by shanethegooner** [comment] 2023-02-19 21:24
I do actually have a YouTube add-on! Disabling that removed the YouTube line but now going to http://192.168.50.19:32500/resources?token=>PLEXTOKEN is empty.

`<MediaContainer size="0"> </MediaContainer>`

I restarted the Firestick too but it didn't help.

**Comment by mdhiggins** [comment] 2023-02-19 21:27
Is there an option to install Plex from the google play store instead of say the Fire TV store? Curious if there's any difference there

**Comment by shanethegooner** [comment] 2023-02-19 21:28
Sorry, forgot to answer that. No, only the Amazon app store but sideloading apks is possible.

**Comment by mdhiggins** [comment] 2023-02-19 21:42
Might be worth it to try and sideload the regular Plex for android tv APK and see if that behaves any differently

https://www.apkmirror.com/apk/plex-inc/plex/

**Comment by shanethegooner** [comment] 2023-02-19 21:43
Alright, I'll give that a go and report back in the morning, thanks for your help so far, it's appreciated!

**Comment by tchirou** [comment] 2023-02-19 22:29
Just my 2 cents :
I have a shield tv and a fire tv stick 4k max (plex downloaded from the stores) 
Plex media server and Plexautoskip are in docker containers on a Synology nas and it works 
So this is not a hardware issue

**Comment by ShanaryS** [comment] 2023-02-20 02:31
I have a Chromecast with GoogleTV (Android) at I have the exact same ```<MediaContainer size="0"> </MediaContainer>``` issue and the autoskip doesn't work on that device. I have autoskip in a docker container but not plex media server.

**Comment by mdhiggins** [comment] 2023-02-20 02:35
The `<MediaContainer size="0"> </MediaContainer>` is coming directly from the player, so it probably has nothing to do with the server 

Ultimately this is a Plex client problem, see https://support.plex.tv/articles/201812803-plex-companion-remote-control-issues/ but if the API isn't working on their client there's not much I can do

**Comment by shanethegooner** [comment] 2023-02-20 13:05
Yeah I think it's just a dead end for me, no idea why. Tried sideloading a few different versions, none of which worked. Thanks for the help though!

**Comment by mdhiggins** [comment] 2023-02-20 22:09
Out of curiosity, on these devices that are reporting nothing via the API, can you cast to them from your phone via the Plex mobile app and/or use the Plex mobile app to remote control playback (seek, next, pause etc)?

**Comment by ShanaryS** [comment] 2023-02-20 23:16
I can cast and control my Chromecast from my phone. However the skip intro doesn't seem to be available at all when casting.

This is what the logs return:
```
2023-02-20 18:12:24 - __main__ - INFO - Found new session 13 [2036] (Big Mouth s01e02 - Everybody Bleeds) Chromecast|8i5s9r2zkpq6qpnp4fjmb74h viewOffset 31000 StoneColeQ on Plex Cast, sessions: 0
2023-02-20 18:12:25 - __main__ - DEBUG - Updating session 13 [2036] (Big Mouth s01e02 - Everybody Bleeds) Chromecast|8i5s9r2zkpq6qpnp4fjmb74h [playing] viewOffset 31000, old 31000, diff 0ms (0s since last update)
2023-02-20 18:12:31 - __main__ - DEBUG - Updating session 13 [2036] (Big Mouth s01e02 - Everybody Bleeds) Chromecast|8i5s9r2zkpq6qpnp4fjmb74h [playing] viewOffset 37000, old 37263, diff -263ms (6s since last update)
2023-02-20 18:12:41 - __main__ - DEBUG - Updating session 13 [2036] (Big Mouth s01e02 - Everybody Bleeds) Chromecast|8i5s9r2zkpq6qpnp4fjmb74h [playing] viewOffset 47000, old 47008, diff -8ms (10s since last update)
2023-02-20 18:12:51 - __main__ - DEBUG - Updating session 13 [2036] (Big Mouth s01e02 - Everybody Bleeds) Chromecast|8i5s9r2zkpq6qpnp4fjmb74h [playing] viewOffset 57000, old 56978, diff 22ms (9s since last update)
2023-02-20 18:12:57 - __main__ - INFO - Found skippable marker intro for media 13 [2036] (Big Mouth s01e02 - Everybody Bleeds) Chromecast|8i5s9r2zkpq6qpnp4fjmb74h with range 59176(+3000)-91454(+1000) and viewOffset 62550
2023-02-20 18:12:57 - __main__ - INFO - Seeking Plex Cast player playing 13 [2036] (Big Mouth s01e02 - Everybody Bleeds) Chromecast|8i5s9r2zkpq6qpnp4fjmb74h from 62551 to 92454
2023-02-20 18:12:57 - __main__ - ERROR - BadRequest Error, see https://github.com/mdhiggins/PlexAutoSkip/wiki/Troubleshooting#badrequest-error
2023-02-20 18:12:57 - __main__ - DEBUG - Modifying client for direct connection using baseURL http://10.10.10.121:32500 for player Chromecast (None)
2023-02-20 18:12:57 - __main__ - INFO - Seeking Plex Cast player playing 13 [2036] (Big Mouth s01e02 - Everybody Bleeds) Chromecast|8i5s9r2zkpq6qpnp4fjmb74h from 62552 to 92454
2023-02-20 18:12:57 - __main__ - ERROR - Exception, removing from cache to prevent false triggers, will be restored with next sync
Traceback (most recent call last):
  File "/usr/local/pas/resources/skipper.py", line 255, in seekPlayerTo
    mediaWrapper.seekTo(targetOffset, player)
  File "/usr/local/pas/resources/mediaWrapper.py", line 326, in seekTo
    player.seekTo(offset)
  File "/usr/local/pas/venv/lib/python3.10/site-packages/plexapi/client.py", line 377, in seekTo
    self.sendCommand('playback/seekTo', offset=offset, type=mtype)
  File "/usr/local/pas/venv/lib/python3.10/site-packages/plexapi/client.py", line 232, in sendCommand
    return query(key, headers=headers)
  File "/usr/local/pas/venv/lib/python3.10/site-packages/plexapi/server.py", line 755, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (500) internal_server_error; https://10-10-10-100.9875dcab10e94b82897e752a9fe30f70.plex.direct:32400/player/playback/seekTo?commandID=1&offset=92454&type=video <?xml version='1.0' encoding='utf-8'?> <Response code="2000" status="FrameworkException: Unable to find player with identifier 8i5s9r2zkpq6qpnp4fjmb74h">   <Traceback>Traceback (most recent call last):   File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-02189b09f\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 843, in handle_request     result = f(**d)   File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-02189b09f\System.bundle\Contents\Code\playerservice.py", line 50, in process_remote_command     raise FrameworkException('Unable to find player with identifier %s' % identifier) FrameworkException: Unable to find player with identifier 8i5s9r2zkpq6qpnp4fjmb74h </Traceback> </Response> 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/pas/resources/skipper.py", line 223, in _seekTo
    self.seekPlayerTo(mediaWrapper.player, mediaWrapper, targetOffset)
  File "/usr/local/pas/resources/skipper.py", line 263, in seekPlayerTo
    return self.seekPlayerTo(self.recoverPlayer(player), mediaWrapper, targetOffset, pq)
  File "/usr/local/pas/resources/skipper.py", line 255, in seekPlayerTo
    mediaWrapper.seekTo(targetOffset, player)
  File "/usr/local/pas/resources/mediaWrapper.py", line 326, in seekTo
    player.seekTo(offset)
  File "/usr/local/pas/venv/lib/python3.10/site-packages/plexapi/client.py", line 377, in seekTo
    self.sendCommand('playback/seekTo', offset=offset, type=mtype)
  File "/usr/local/pas/venv/lib/python3.10/site-packages/plexapi/client.py", line 232, in sendCommand
    return query(key, headers=headers)
  File "/usr/local/pas/venv/lib/python3.10/site-packages/plexapi/client.py", line 192, in query
    raise NotFound(message)
plexapi.exceptions.NotFound: (404) not_found; http://10.10.10.121:32500/player/playback/seekTo?commandID=2&offset=92454&type=video Failure: 404 Not Found
 
2023-02-20 18:12:57 - __main__ - DEBUG - Deleting session 13 [2036] (Big Mouth s01e02 - Everybody Bleeds) Chromecast|8i5s9r2zkpq6qpnp4fjmb74h, sessions: 0
2023-02-20 18:13:00 - __main__ - INFO - Found new session 13 [2036] (Big Mouth s01e02 - Everybody Bleeds) Chromecast|8i5s9r2zkpq6qpnp4fjmb74h viewOffset 65000 StoneColeQ on Plex Cast, sessions: 0
2023-02-20 18:13:01 - __main__ - DEBUG - Updating session 13 [2036] (Big Mouth s01e02 - Everybody Bleeds) Chromecast|8i5s9r2zkpq6qpnp4fjmb74h [paused] viewOffset 66000, old 65000, diff 1000ms (1s since last update)
2023-02-20 18:13:02 - __main__ - DEBUG - Updating session 13 [2036] (Big Mouth s01e02 - Everybody Bleeds) Chromecast|8i5s9r2zkpq6qpnp4fjmb74h [stopped] viewOffset 66000, old 66000, diff 0ms (0s since last update)
2023-02-20 18:13:03 - __main__ - DEBUG - Session 13 [2036] (Big Mouth s01e02 - Everybody Bleeds) Chromecast|8i5s9r2zkpq6qpnp4fjmb74h has been marked as ended with viewOffset 66000 and state stopped, removing
2023-02-20 18:13:03 - __main__ - DEBUG - Deleting session 13 [2036] (Big Mouth s01e02 - Everybody Bleeds) Chromecast|8i5s9r2zkpq6qpnp4fjmb74h, sessions: 0
```

Maybe it's possible to control the casted device through the phone?

**Comment by mdhiggins** [comment] 2023-02-20 23:24
The issue here is that the remote control / plex companion / advertise as player (whatever you want to call it) API isn't working

It gets a little confusing here because the Chromecast can receive plex casts without actually using the Plex app at all

I guess the better test is, can you start playing something on one of these devices inside the plex app on that device, and then connect to that device using your phone and see the playback data and manipulate it.

Here's the steps to test

1. Open plex app on Android TV
2. Play something
3. Open plex on mobile device
4. Press cast button and choose android device from step 1

Now you should see whatever you played from step 1 showing up like it was cast and be able to seek/play/stop etc. This means the remote control API is working. I would think that if the API reports nothing that this feature shouldn't work

Also, I think I have an old chromecast somewhere, what device/version are you guys using? I can try and set it up and see if I can reproduce this

**Comment by shanethegooner** [comment] 2023-02-20 23:31
> Out of curiosity, on these devices that are reporting nothing via the API, can you cast to them from your phone via the Plex mobile app and/or use the Plex mobile app to remote control playback (seek, next, pause etc)?

Hey! Just checked casting from my phone to the Firestick and it doesn't show up. I can see the Firestick from other apps, like the official remote app or casting from YouTube so there's clearly something wrong with Plex on my Firestick.

**Comment by ShanaryS** [comment] 2023-02-21 02:11
My devices are Chromecast with Google TV (4K) and Samsung S95B. Autoskip works on the S95B Plex app (Tizen OS) but not the chromecast (Android TV).

For your steps with the chromecast, it stopped playing the video and showed the plex casting screen (responsive to iphone navigation). So essentially you were right, it can't receive commands like a remote control. This is proven by the fact it works as you described when I do it on my S95B. It doesn't stop playback and just allows me to control it.

**Comment by mdhiggins** [comment] 2023-02-27 14:37
Closing this out, seems like primarily this is a plex companion bug, if I find any new workarounds or anything I'll share

**Closed as completed by mdhiggins** 2023-02-27 14:37 UTC

**Comment by ShanaryS** [comment] 2023-09-06 01:51
I just wanted to update that Plex finally added the setting to advertise as player on July 3rd. Should be fixed for AndroidTV now.

https://forums.plex.tv/t/plex-for-android/29115/474

**Comment by shanethegooner** [comment] 2023-09-08 05:23
> I just wanted to update that Plex finally added the setting to advertise as player on July 3rd. Should be fixed for AndroidTV now.
> 
> https://forums.plex.tv/t/plex-for-android/29115/474

Thanks for the heads up! 

It now works great with my Fire TV Stick. Wouldn't work at first but cloning the repository again did the job.
